name: Node.js CI
on: [push, pull_request]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Node
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci

      # Install Ruby and Gems
      - name: Install Ruby
        uses: ruby/setup-ruby@1
        with:
          ruby-version: 2.2.7
      - run: gem install public_suffix -v 2.0.5
      - run: gem install ruby_dep -v 1.3.1
      - run: gem install ffi -v 1.12.2
      - run: install jekyll -v 3.6.2

      # Install and build, then test
      - run: npm install
      - run: npm run build
      - run: sudo apt-get install xvfb
      - run: xvfb-run --auto-servernum npm test