name: CI Tests
on: [push, pull_request]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Node
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # only needed while we are using a node
      # version below 15
      - name: Install NPM 7
        run: npm install -g npm@7

      - run: npm ci

      # Run tests
      - run: npm run test
